name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.25.1"
  JUST_VERSION: "1.45.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use golang
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup just
        uses: extractions/setup-just@v3
        with:
          just-version: ${{ env.JUST_VERSION }}

      - name: Install golangci
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.5.0

      - name: run lint with just
        run: just lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use golang
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup just
        uses: extractions/setup-just@v3
        with:
          just-version: ${{ env.JUST_VERSION }}

      - name: Run tests
        run: just ut

      - name: Upload Unit Test Coverage
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v6
        with:
          name: coverage
          path: coverage.out
          retention-days: 1

  coverage-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout
      pull-requests: write # for octocov to post comments
      actions: read # for octocov to parse test execution time
    needs: test
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download Unit Test Coverage
        uses: actions/download-artifact@v7
        with:
          name: coverage

      - name: Coverage Report
        uses: k1LoW/octocov-action@v1
        with:
          github-token: ${{ github.token }}
